apiVersion: apps/v1
kind: Deployment
metadata:
  name: 2048-game
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mygame  # This matches the label in the pod template
  template:
    metadata:
      labels:
        app: mygame  # Label for the pods
    spec:
      containers:
      - name: 2048-Container
        image: blackicebird/2048
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: mygame
spec:
  selector:
    app: mygame  # This should match the label in the Deployment (app: mygame)
  ports:
  - port: 8000
    targetPort: 80  # Ensure the targetPort matches the containerPort
  type: LoadBalancer
